services:
  - type: web
    name: shellguard-live-demo
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: SHELLGUARD_DISABLE_AUTH
        value: "1"
      - key: SHELLGUARD_FAIL_POLICY
        value: "fail_open"
